kind: Service
apiVersion: v1
metadata:
  name: ${GOOGLE_PROJECT_ID}-stag
spec:
  selector:
    app: ${GOOGLE_PROJECT_ID}-stag
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${GOOGLE_PROJECT_ID}-stag
  labels:
    app: ${GOOGLE_PROJECT_ID}-stag
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${GOOGLE_PROJECT_ID}-stag
  template:
    metadata:
      labels:
        app: ${GOOGLE_PROJECT_ID}-stag
    spec:
      containers:
        - name: ${GOOGLE_PROJECT_ID}-stag
          image: eu.gcr.io/${GOOGLE_PROJECT_ID}/backendrepo:${CIRCLE_SHA1}
          env:
            - name: DATASOURCE_URL
              value: ${DATASOURCE_URL}
            - name: DATASOURCE_USERNAME
              value: ${DATASOURCE_USERNAME}
            - name: DATASOURCE_PASSWORD
              value: ${DATASOURCE_PASSWORD}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP